import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import UserDropdown from "./user-dropdown";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <Theme accentColor="crimson" grayColor="slate" radius="large" scaling="110%" appearance="dark">
            <nav className="h-20 flex items-center justify-between p-4 text-white bg-black/40 backdrop-blur border-b border-white/10">
              <Link
                href="/"
                className="font-bold text-2xl flex gap-1 items-center"
              >
                <ChartColumnBigIcon className="text-red-500" /> NextCash
              </Link>
              <div>
                <SignedOut>
                  <div className="flex items-center">
                    <Button asChild variant="link" className="text-white">
                      <SignInButton />
                    </Button>
                    <Button asChild variant="link" className="text-white">
                      <SignUpButton />
                    </Button>
                  </div>
                </SignedOut>
                <SignedIn>
                  <div className="flex items-center gap-3">
                    <Button asChild variant="outline" className="text-white border-white/20">
                      <Link href="/gemini">Gemini</Link>
                    </Button>
                    <UserDropdown />
                  </div>
                </SignedIn>
              </div>
            </nav>
            {children}
            <Toaster />
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
